package cryptoutils

import (
	"errors"
	"fmt"
	"io"

	"golang.org/x/crypto/argon2"
	"golang.org/x/crypto/hkdf"
	"golang.org/x/crypto/pbkdf2"
	"golang.org/x/crypto/scrypt"
)

// ErrKDFParameters reports invalid parameters or an exceeded resource budget.
var ErrKDFParameters = errors.New("cryptoutils: invalid KDF parameters")

const (
	MaxKDFOutput = 64 * 1024
	MaxKDFInput  = 1 << 20
	maxKDFMemory = 256 << 20
)

// PBKDF2Options specifies HMAC hash, iteration count and output length in bytes.
// A nil options pointer selects DefaultPBKDF2Options; otherwise every field is used.
type PBKDF2Options struct {
	Hash       string
	Iterations int
	KeyLength  int
}

func DefaultPBKDF2Options() PBKDF2Options {
	return PBKDF2Options{Hash: "sha256", Iterations: 600000, KeyLength: 32}
}

type HKDFOptions struct {
	Hash      string
	KeyLength int
}

func DefaultHKDFOptions() HKDFOptions { return HKDFOptions{Hash: "sha256", KeyLength: 32} }

// ScryptOptions specifies CPU/memory cost N, block size R, parallelization P,
// and output length in bytes. N must be a power of two greater than one.
type ScryptOptions struct {
	N, R, P   int
	KeyLength int
}

func DefaultScryptOptions() ScryptOptions {
	return ScryptOptions{N: 32768, R: 8, P: 1, KeyLength: 32}
}

// Argon2idOptions specifies passes, memory in KiB, lanes and output bytes.
// Non-nil options are validated before calling Argon2 or allocating its memory.
type Argon2idOptions struct {
	Time, Memory, Threads, KeyLength int
}

func DefaultArgon2idOptions() Argon2idOptions {
	return Argon2idOptions{Time: 3, Memory: 64 * 1024, Threads: 4, KeyLength: 32}
}

func checkKDFInput(inputs ...[]byte) error {
	for _, input := range inputs {
		if len(input) > MaxKDFInput {
			return fmt.Errorf("%w: each input is limited to %d bytes", ErrKDFParameters, MaxKDFInput)
		}
	}
	return nil
}

func checkKDFLength(length int) error {
	if length < 1 || length > MaxKDFOutput {
		return fmt.Errorf("%w: output must be 1..%d bytes", ErrKDFParameters, MaxKDFOutput)
	}
	return nil
}

// PBKDF2 derives raw key bytes. Callers provide and store a salt; no random salt
// is generated by this low-level KDF. SHA-256 is the default HMAC hash.
func PBKDF2(password, salt []byte, options *PBKDF2Options) ([]byte, error) {
	o := DefaultPBKDF2Options()
	if options != nil {
		o = *options
	}
	if err := checkKDFInput(password, salt); err != nil {
		return nil, err
	}
	if err := checkKDFLength(o.KeyLength); err != nil {
		return nil, err
	}
	factory, err := hashFactory(o.Hash)
	if err != nil {
		return nil, err
	}
	blocks := (o.KeyLength + factory().Size() - 1) / factory().Size()
	if o.Iterations < 1 || o.Iterations > 2000000 || o.Iterations > 4000000/blocks {
		return nil, fmt.Errorf("%w: PBKDF2 requires 1..2000000 iterations and at most 4000000 block-iterations", ErrKDFParameters)
	}
	return pbkdf2.Key(password, salt, o.Iterations, o.KeyLength, factory), nil
}

// HKDF derives raw key bytes from existing key material, salt and context info.
// HKDF is not a password-hardening function.
func HKDF(secret, salt, info []byte, options *HKDFOptions) ([]byte, error) {
	o := DefaultHKDFOptions()
	if options != nil {
		o = *options
	}
	if err := checkKDFInput(secret, salt, info); err != nil {
		return nil, err
	}
	if err := checkKDFLength(o.KeyLength); err != nil {
		return nil, err
	}
	factory, err := hashFactory(o.Hash)
	if err != nil {
		return nil, err
	}
	if o.KeyLength > 255*factory().Size() {
		return nil, fmt.Errorf("%w: HKDF output exceeds 255 digest blocks", ErrKDFParameters)
	}
	out := make([]byte, o.KeyLength)
	if _, err := io.ReadFull(hkdf.New(factory, secret, salt, info), out); err != nil {
		return nil, fmt.Errorf("cryptoutils: HKDF: %w", err)
	}
	return out, nil
}

// Scrypt derives raw key bytes with bounded CPU and memory costs.
func Scrypt(password, salt []byte, options *ScryptOptions) ([]byte, error) {
	o := DefaultScryptOptions()
	if options != nil {
		o = *options
	}
	if err := checkKDFInput(password, salt); err != nil {
		return nil, err
	}
	if err := checkKDFLength(o.KeyLength); err != nil {
		return nil, err
	}
	if o.N < 2 || o.N > 1<<20 || o.N&(o.N-1) != 0 || o.R < 1 || o.R > 32 || o.P < 1 || o.P > 16 {
		return nil, fmt.Errorf("%w: scrypt requires power-of-two N in 2..1048576, r in 1..32, p in 1..16", ErrKDFParameters)
	}
	n, r, parallel := uint64(o.N), uint64(o.R), uint64(o.P)
	memory := 128*r*n + 128*r*parallel + 256*r + uint64(o.KeyLength)
	if memory > maxKDFMemory || n*r*parallel > 1<<24 {
		return nil, fmt.Errorf("%w: scrypt exceeds 256 MiB memory or N*r*p work budget", ErrKDFParameters)
	}
	key, err := scrypt.Key(password, salt, o.N, o.R, o.P, o.KeyLength)
	if err != nil {
		return nil, fmt.Errorf("cryptoutils: scrypt: %w", err)
	}
	return key, nil
}

func validateArgon2idOptions(o Argon2idOptions) error {
	if o.Time < 1 || o.Time > 10 || o.Memory < 8 || o.Memory > 256*1024 || o.Threads < 1 || o.Threads > 16 || o.KeyLength < 4 || o.KeyLength > 1024 {
		return fmt.Errorf("%w: Argon2id requires time 1..10, memory 8..262144 KiB, threads 1..16, output 4..1024 bytes", ErrKDFParameters)
	}
	if o.Memory < 8*o.Threads || uint64(o.Memory)*uint64(o.Time) > 512*1024 {
		return fmt.Errorf("%w: Argon2id requires memory >= 8*threads and memory*time <= 524288 KiB-passes", ErrKDFParameters)
	}
	return nil
}

// Argon2id derives raw key bytes using Argon2id version 19. The salt must contain
// at least 8 bytes. Use HashArgon2id for a password hash with random salt and
// self-contained parameters, rather than storing a bare derived key.
func Argon2id(password, salt []byte, options *Argon2idOptions) ([]byte, error) {
	o := DefaultArgon2idOptions()
	if options != nil {
		o = *options
	}
	if err := checkKDFInput(password, salt); err != nil {
		return nil, err
	}
	if len(salt) < 8 {
		return nil, fmt.Errorf("%w: Argon2id salt must contain at least 8 bytes", ErrKDFParameters)
	}
	if err := validateArgon2idOptions(o); err != nil {
		return nil, err
	}
	return argon2.IDKey(password, salt, uint32(o.Time), uint32(o.Memory), uint8(o.Threads), uint32(o.KeyLength)), nil
}

// KDF chain methods replace the current data with raw key bytes.
func (p *CryptoData) PBKDF2(salt []byte, options *PBKDF2Options) *CryptoData {
	if p.err != nil {
		return p
	}
	out, err := PBKDF2(p.data, salt, options)
	return p.setKDFResult(out, err)
}

func (p *CryptoData) HKDF(salt, info []byte, options *HKDFOptions) *CryptoData {
	if p.err != nil {
		return p
	}
	out, err := HKDF(p.data, salt, info, options)
	return p.setKDFResult(out, err)
}

func (p *CryptoData) Scrypt(salt []byte, options *ScryptOptions) *CryptoData {
	if p.err != nil {
		return p
	}
	out, err := Scrypt(p.data, salt, options)
	return p.setKDFResult(out, err)
}

func (p *CryptoData) Argon2id(salt []byte, options *Argon2idOptions) *CryptoData {
	if p.err != nil {
		return p
	}
	out, err := Argon2id(p.data, salt, options)
	return p.setKDFResult(out, err)
}

func (p *CryptoData) setKDFResult(out []byte, err error) *CryptoData {
	if err != nil {
		return p.fail(err)
	}
	p.data = out
	return p
}
