package cryptoutils

import (
	"github.com/wave4y/cryptoutils/internal/derivation"
)

// ErrKDFParameters reports invalid parameters or an exceeded resource budget.
var ErrKDFParameters = derivation.ErrKDFParameters

const (
	MaxKDFInput  = derivation.MaxKDFInput
	MaxKDFOutput = derivation.MaxKDFOutput
)

// PBKDF2Options specifies HMAC hash, iteration count and output length in bytes.
// A nil options pointer selects DefaultPBKDF2Options; otherwise every field is used.
type PBKDF2Options struct {
	Hash       string
	Iterations int
	KeyLength  int
}

func DefaultPBKDF2Options() PBKDF2Options { return PBKDF2Options(derivation.DefaultPBKDF2Options()) }

type HKDFOptions struct {
	Hash      string
	KeyLength int
}

func DefaultHKDFOptions() HKDFOptions { return HKDFOptions(derivation.DefaultHKDFOptions()) }

// ScryptOptions specifies CPU/memory cost N, block size R, parallelization P,
// and output length in bytes. N must be a power of two greater than one.
type ScryptOptions struct {
	N, R, P   int
	KeyLength int
}

func DefaultScryptOptions() ScryptOptions { return ScryptOptions(derivation.DefaultScryptOptions()) }

// Argon2idOptions specifies passes, memory in KiB, lanes and output bytes.
// Non-nil options are validated before calling Argon2 or allocating its memory.
type Argon2idOptions struct {
	Time, Memory, Threads, KeyLength int
}

func DefaultArgon2idOptions() Argon2idOptions {
	return Argon2idOptions(derivation.DefaultArgon2idOptions())
}

// PBKDF2 derives raw key bytes. Callers provide and store a salt; no random salt
// is generated by this low-level KDF. SHA-256 is the default HMAC hash.
func PBKDF2(password, salt []byte, options *PBKDF2Options) ([]byte, error) {
	return derivation.PBKDF2(password, salt, (*derivation.PBKDF2Options)(options))
}

// HKDF derives raw key bytes from existing key material, salt and context info.
// HKDF is not a password-hardening function.
func HKDF(secret, salt, info []byte, options *HKDFOptions) ([]byte, error) {
	return derivation.HKDF(secret, salt, info, (*derivation.HKDFOptions)(options))
}

// Scrypt derives raw key bytes with bounded CPU and memory costs.
func Scrypt(password, salt []byte, options *ScryptOptions) ([]byte, error) {
	return derivation.Scrypt(password, salt, (*derivation.ScryptOptions)(options))
}

// Argon2id derives raw key bytes using Argon2id version 19. The salt must contain
// at least 8 bytes. Use HashArgon2id for a password hash with random salt and
// self-contained parameters, rather than storing a bare derived key.
func Argon2id(password, salt []byte, options *Argon2idOptions) ([]byte, error) {
	return derivation.Argon2id(password, salt, (*derivation.Argon2idOptions)(options))
}

// KDF chain methods replace the current data with raw key bytes.
func (p *CryptoData) PBKDF2(salt []byte, options *PBKDF2Options) *CryptoData {
	if p.err != nil {
		return p
	}
	out, err := PBKDF2(p.data, salt, options)
	return p.setKDFResult(out, err)
}

func (p *CryptoData) HKDF(salt, info []byte, options *HKDFOptions) *CryptoData {
	if p.err != nil {
		return p
	}
	out, err := HKDF(p.data, salt, info, options)
	return p.setKDFResult(out, err)
}

func (p *CryptoData) Scrypt(salt []byte, options *ScryptOptions) *CryptoData {
	if p.err != nil {
		return p
	}
	out, err := Scrypt(p.data, salt, options)
	return p.setKDFResult(out, err)
}

func (p *CryptoData) Argon2id(salt []byte, options *Argon2idOptions) *CryptoData {
	if p.err != nil {
		return p
	}
	out, err := Argon2id(p.data, salt, options)
	return p.setKDFResult(out, err)
}

func (p *CryptoData) setKDFResult(out []byte, err error) *CryptoData {
	if err != nil {
		return p.fail(err)
	}
	p.data = out
	return p
}
